---
title: "OpenCPU"
author: "Witek ten Hove"
date: "3/4/2017"
output:
   html_document:
      theme: spacelab
      highlight: tango
---

# Building dynamic web objects using [OpenCPU](https://www.opencpu.org/)

<video width="800" height="600" controls>
  <source src="video/demo.mp4" type="video/mp4">
</video><br>

With OpenCPU you can use R as a data source for JavaScript objects (e.g. charts). The structure is as follows:

1. You have a server running OpenCPU, R and RStudio. See [this](http://jeroenooms.github.io/opencpu-manual/opencpu-server.pdf) tutorial for instructions. My server runs [here](http://ec2-34-252-17-179.eu-west-1.compute.amazonaws.com/ocpu/test/).
2. The [library](http://ec2-34-252-17-179.eu-west-1.compute.amazonaws.com/ocpu/library/) folder of R contains packages with functions that can be accessed as an API.
3. You can [add users](https://www.digitalocean.com/community/tutorials/how-to-set-up-rstudio-on-an-ubuntu-cloud-server) to the server who can build their [own packages](http://ec2-34-252-17-179.eu-west-1.compute.amazonaws.com/ocpu/user/rstudio/library/) with their own functions.
4. The functions in the package can be accessed via a server [url](http://ec2-34-252-17-179.eu-west-1.compute.amazonaws.com/ocpu/user/rstudio/library/hellorobert/R/dataTest/print). Ending it with `/json` returns a [json file](http://ec2-34-252-17-179.eu-west-1.compute.amazonaws.com/ocpu/user/rstudio/library/hellorobert/R/dataTest/json).
5. This json file can be used as input for a JavaScript object, for instance a [chart](http://www.smartedu.nl/opencpu/test.html). See source code of this file.
<br><br>

    <style>
        .bar {
            fill: steelblue;
        }
        .bar:hover {
            fill: brown;
        }
        .axis {
            font: 10px sans-serif;
        }
        .axis path,
        .axis line {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }
    </style>
    <div align="center">
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="http://d3js.org/d3.v3.min.js"></script>
    <script align="center">
        //When Document is Ready
        $(function() {
            //This part prepares the url string
            var resultsUrlPrefix = "http://ec2-34-252-17-179.eu-west-1.compute.amazonaws.com",
                url = resultsUrlPrefix + "/ocpu//user/rstudio/library/hellorobert/R/dataTest";
            //The following makes posts the url to the opencpu server on AWS and
            //concatenates the reply into a result link
            $.post(url,
                    function(data) {

                        var statResultsLink = resultsUrlPrefix + data.toString().match(/.+\/.val/m) + "\/json";
                        $("#json1").attr("href", statResultsLink)

                        // Build chart (d3.js)
                        // set the dimensions of the canvas
                        var margin = {
                                top: 20,
                                right: 20,
                                bottom: 70,
                                left: 200
                            },
                            width = 600 - margin.left - margin.right,
                            height = 300 - margin.top - margin.bottom;


                        // set the ranges
                        var x = d3.scale.ordinal().rangeRoundBands([0, width], .05);

                        var y = d3.scale.linear().range([height, 0]);

                        // define the axis
                        var xAxis = d3.svg.axis()
                            .scale(x)
                            .orient("bottom")


                        var yAxis = d3.svg.axis()
                            .scale(y)
                            .orient("left")
                            .ticks(10);


                        // add the SVG element
                        var svg = d3.select("body").append("svg")
                            .attr("width", width + margin.left + margin.right)
                            .attr("height", height + margin.top + margin.bottom)
                            .append("g")
                            .attr("transform",
                                "translate(" + margin.left + "," + margin.top + ")");


                        // load the data

                        d3.json(statResultsLink, function(error, data) {

                            data.forEach(function(d) {
                                d.namen = d.namen;
                                d.leeftijd = +d.leeftijd;
                            });

                            // scale the range of the data
                            x.domain(data.map(function(d) {
                                return d.namen;
                            }));
                            y.domain([0, d3.max(data, function(d) {
                                return d.leeftijd;
                            })]);

                            // add axis
                            svg.append("g")
                                .attr("class", "x axis")
                                .attr("transform", "translate(0," + height + ")")
                                .call(xAxis)
                                .selectAll("text")
                                .style("text-anchor", "end")
                                .attr("dx", "-.8em")
                                .attr("dy", "-.55em")
                                .attr("transform", "rotate(-90)");

                            svg.append("g")
                                .attr("class", "y axis")
                                .call(yAxis)
                                .append("text")
                                .attr("transform", "rotate(-90)")
                                .attr("y", 5)
                                .attr("dy", ".71em")
                                .style("text-anchor", "end")
                                .text("Leeftijd");


                            // Add bar chart
                            svg.selectAll("bar")
                                .data(data)
                                .enter().append("rect")
                                .attr("class", "bar")
                                .attr("x", function(d) {
                                    return x(d.namen);
                                })
                                .attr("width", x.rangeBand())
                                .attr("y", function(d) {
                                    return y(d.leeftijd);
                                })
                                .attr("height", function(d) {
                                    return height - y(d.leeftijd);
                                });

                        });

                    })
                .error(function(jqXHR, status, error) {
                    alert(jqXHR.responseText);
                });
        });
    </script>
    <a id="json1" target="_blank">JSON</a>
<div>